### PR TITLE
Fixed black key positioning, added Montserrat font

### LINKED ISSUE #19: Black key position is offset (absolute positioning)
image
# Possible Fixes
- Include both black and white keys in one div
- Modify margin-calculation function
- Ternary operator in .map() for black and white keys

### PR DESCRIPTION
**Pull request by brunogrcsada**
image

- [x] Displays keyboard key pressed on the note bubble
- [x] Logo text displays on the top-right corner
- [x] Black keys are positioned correctly
- [ ] Display equivalent keyboard letters on black keys
- [ ] Make keys larger

Closes #19 #6

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -32,30 +37,42 @@ function App() {
...
-         else return <div onMouseDown={() => play({ id: d.toString() })} style={{marginLeft: ((((i-(18 * 4))*2)*30)).toString() + 'px'}} id='black_key'/>
-       })} 
+        {keyboard.map((d, i) => 
+            d !== d.toString().toUpperCase() ?
+                <div id={keyboard[i].toString()} className='section'>
+                  <div onMouseDown={() => play({ id: d.toString() })} id={i} className='key'>
+                        <span className='noselect'>{d}</span>
+                  </div>
+                  {(() => {
+                     if(i + 1 < keyboard.length && keyboard[i + 1] === keyboard[i + 1].toString().toUpperCase()) {
```
Comment (melissalupu) [inline src/App.js:61]: More logical!

**Review by melissalupu — APPROVED** [review]

**Review by flynnn231 — APPROVED** [review]

**Review by Jsimpada — APPROVED** [review]
Good addition of fonts and the codes clearer too. Nice
